language: bash

services: docker

os: windows

before_script:
  - docker version
  - env | sort

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      # build:
      docker build --tag rustvmm/dev:v3_amd64 --file Dockerfile.amd64 .
      docker run --rm rustvmm/dev:v3_amd64 cargo --version
    )

